# Generated by Django 5.0 on 2025-11-21 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО студента')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.IntegerField(verbose_name='Математика')),
                ('physics', models.IntegerField(verbose_name='Физика')),
                ('programming', models.IntegerField(verbose_name='Программирование')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='Студент')),
            ],
        ),
    ]
